export enum IpcChannel {
    ClearCaches = "ClearCaches",
    EscapePressed = "EscapePressed",
    Execute = "Execute",
    GetExecutionContext = "GetExecutionContext",
    GetSettings = "GetSettings",
    MainWindowShown = "MainWindowShown",
    OpenLocation = "OpenLocation",
    RescanFinished = "RescanFinished",
    RescanStarted = "RescanStarted",
    Search = "Search",
    SettingsUpdated = "SettingsUpdated",
    TrayIconEvent = "TrayIconEvent",
    UeliCommandEvent = "UeliCommandEvent",
    UpdateSettings = "UpdateSettings",
}
